### ISSUE TITLE
environment dependencies (yaml-files) are not downloadable 

### ISSUE THREAD

**Issue by edissepo** [medema-group/BiG-MAP#1]
The yaml files are a specific dump of dependencies which renders some packages not to be found.

Error:
ResolvePackageNotFound:
    - openssl==1.1.1=h7b6447c_0

Solve:
Provide top-level dependencies.

**Comment by HAugustijn** [comment]
Thank you for notifying us of this issue. The yaml files have now been updated to include only the top-level dependencies.
