### ISSUE TITLE
normalization to control group for log2 fold change

### ISSUE THREAD

**Issue by choon-sim** [medema-group/BiG-MAP#11]
Hi, thanks for the wonderful tool.
In the differential abundance analysis in BiG-MAP.analyse.py, it may be nice to be able to specify which is the control group so that the log2 fold change is correctly normalized to the control group.

**Comment by HAugustijn** [comment]
Thank you for your suggestion! In the analyse module, the group listed second after the -g flag can be considered the control group. This is also written in the description of the analyse module.
