### ISSUE TITLE
Add one in, have to re-run BiG-MAP.map.py?

### ISSUE THREAD

**Issue by flashton2003** [medema-group/BiG-MAP#19]
Hello,

I have an existing big-map analysis of ~150 metagenomes, and I want to add 10 more metagenomes into the analysis

Do I have to run BiG-MAP.map.py with all 160 metagenomes in order to create a unified biom file for analysis with big-map.analyse?

Or is there a way to combine the bioms from different runs into a single file?

Thanks,

Phil

**Comment by HAugustijn** [comment]
Unfortunately, there is no easy way to merge just the two biom files. What you can do is to put all the result files into one directory and rerun BiG-MAP.map on this folder. It will not repeat all the mapping steps, but it will merge everything into one biom file. For this, be sure that all files are described in the metadata or some information might be missing.

**Comment by flashton2003** [comment]
Thanks for this. I tried that once, but it seemed to repeat the samples that had already been run.

I just took a quick look at the code, and it seems to be checking for the existence of the SAM file (L160 BiG-MAP.map.py), but this is in the `outdir`, and perhaps when the code finishes and it gets moved to `bowtie2-map-results` then it doesn't find it the second time?

Also, storing all the SAM files is quite "greedy" for hard drive space.

Sorry for all the issues, they're just minor things really, I'm getting some interesting results from big-map, and that's why I'm running it so much to find all these edge cases :-D

**Comment by HAugustijn** [comment]
> I just took a quick look at the code, and it seems to be checking for the existence of the SAM file (L160 BiG-MAP.map.py), but this is in the outdir, and perhaps when the code finishes and it gets moved to bowtie2-map-results then it doesn't find it the second time?

In this case, you'll have to move all the results files into one directory, which means that the files need to be moved out of their subdirectory (like the `bowtie2-map-results` folder). Then the code won't rerun everything. 

> Sorry for all the issues, they're just minor things really, I'm getting some interesting results from big-map, and that's why I'm running it so much to find all these edge cases :-D

No problem. I'm glad the results seem interesting!
