### ISSUE TITLE
Possible to make a release for bioconda recipe?

### ISSUE THREAD

**Issue by SantaMcCloud** [medema-group/BiG-MAP#25]
Hello,

currently I'm working to create a wrapper for BiG-MAP which then should be added to Galaxy (https://usegalaxy.org), an open source tool collection.

For creating a wrapper I need to also write a bioconda recipe, but for the recipe I need to have a release from this GitHub.
Is it possible to make a release which I can use for the recipe?

Thank you in advance!

**Comment by HAugustijn** [comment]
I've added the release
