### ISSUE TITLE
Readme: unclear steps for BiG-MAP.family.py

### ISSUE THREAD

**Issue by edissepo** [medema-group/BiG-MAP#3]
In the readme tutorial, at the BiG-MAP.family.py -  in the example a pfam folder is provided but no mention as to 1) where this came from and 2) what contents there should be there. Perhaps just a short sentence could clarify on what this folder is and does.

**Comment by victoriapascal** [comment]
Sorry for the inconveniences. I have now included a paragraph to explain more in depth how to install BiG-SCAPE and the Pfam database that uses.
