### ISSUE TITLE
error while running BiG-MAP.family.py:ValueError: substring not found

### ISSUE THREAD

**Issue by razz1618** [medema-group/BiG-MAP#5]
Hi,

After successful installation of BiG-MAP and BIG-SCAPE I tried to run it on my metagenomic contig's ANTISMASH output but ran into following error:

**python3 /home/mcs/soft/BiG-MAP/src/BiG-MAP.family.py -p 30 -D 3.Function/antismash/ -b /home/mcs/soft/BiG-SCAPE/bigscape.py -pf /home/mcs/soft/BiG-SCAPE/ -O 3.Function/antismash/big_map_antismash**
___________Extracting fasta files__________
Traceback (most recent call last):
  File "/home/mcs/soft/BiG-MAP/src/BiG-MAP.family.py", line 1223, in <module>
    main()
  File "/home/mcs/soft/BiG-MAP/src/BiG-MAP.family.py", line 1034, in main
    prot_file, orgID, fasta_header = writefasta(AAseq, "GC_PROT", GC, organism, f, args.outdir)
  File "/home/mcs/soft/BiG-MAP/src/BiG-MAP.family.py", line 252, in writefasta
    organism = organism[organism.index('_') + 1:]
**ValueError: substring not found**

for ANTISMASH run I used **--cb-general --cb-knownclusters --cb-subclusters --asf --pfam2go --genefinding-tool none --genefinding-gff3 dir/containing/gff**

**Comment by sklucas** [comment]
Hello, I received the same error message. My input is a directory containing several AntiSMASH (v5) output subdirectories, each pertaining to a bin in a metagenomic bin collection. I can successfully run BiG-SCAPE separately using the same input.

**Comment by HAugustijn** [comment]
Thanks for informing us about this issue! The problem should be fixed with the latest commit. Let me know if you are still experiencing difficulties when running BiG-MAP.family.

**Comment by razz1618** [comment]
Hi, Now the error seems to be solved but got stuck with another error.Here is the report-

/home/mcs/soft/BiG-MAP/src/BiG-MAP.family.py -p 30 -D 3.Function/antismash/ -b /home/mcs/soft/BiG-SCAPE/bigscape.py -pf /home/mcs/soft/BiG-SCAPE/ -O 3.Function/antismash/big_map_antismash -g True
___________Extracting fasta files__________
________Preparing BiG-SCAPE input__________
Traceback (most recent call last):
  File "/home/mcs/soft/BiG-MAP/src/BiG-MAP.family.py", line 1236, in <module>
    main()
  File "/home/mcs/soft/BiG-MAP/src/BiG-MAP.family.py", line 1117, in main
    movegbk(args.outdir, gbk_file, list_gbkfiles)
  File "/home/mcs/soft/BiG-MAP/src/BiG-MAP.family.py", line 828, in movegbk
    shutil.copy(gbk_file, os.path.join(path, genome))
  File "/home/mcs/miniconda3/envs/BiG-MAP_process/lib/python3.6/shutil.py", line 241, in copy
    copyfile(src, dst, follow_symlinks=follow_symlinks)
  File "/home/mcs/miniconda3/envs/BiG-MAP_process/lib/python3.6/shutil.py", line 104, in copyfile
    raise SameFileError("{!r} and {!r} are the same file".format(src, dst))
**shutil.SameFileError: '3.Function/antismash/big_map_antismash/gbk_files/c_000000000001.region001.gbk' and '3.Function/antismash/big_map_antismash/gbk_files/c_000000000001.region001.gbk' are the same file**
