### ISSUE TITLE
BiG-MAP.analyse- ERROR reading BIOM file

### ISSUE THREAD

**Issue by razz1618** [medema-group/BiG-MAP#8]
Hi,

Thanks for modifying the  BiG-MAP.family script. I  created the GCF files and mapped it via the BiG-MAP.map.py script. When I run the BiG-MAP.analyse.py for plotting,  it shows error while loading the biom file regarding the SampleType column.

Here is the shell output:

python3 /home/mcs/soft/BiG-MAP/src/BiG-MAP.analyse.py --explore --compare -B 3.Function/antismash/big_map_antismash/mapping/biom-results/BiG-MAP.mapcore.metacore.dec.biom -T Metagenomic -M Status -O 3.Function/antismash/big_map_antismash/results/core_genes
__________Loading biom file_______________________
Traceback (most recent call last):
  File "/home/mcs/soft/BiG-MAP/src/BiG-MAP.analyse.py", line 1173, in <module>
    main()
  File "/home/mcs/soft/BiG-MAP/src/BiG-MAP.analyse.py", line 1037, in main
    biom_dict, args.metagroup)
  File "/home/mcs/soft/BiG-MAP/src/BiG-MAP.analyse.py", line 144, in get_sample_type
    **elif sample_type == (sample["metadata"]["SampleType"]).upper():**
**TypeError: 'NoneType' object is not subscriptable**

Here is the output biom file and the metadata file used to create the biom file
[metadata.txt](https://github.com/medema-group/BiG-MAP/files/6738478/metadata.txt)
[BiG-MAP.mapcore.metacore.dec.biom.txt](https://github.com/medema-group/BiG-MAP/files/6738480/BiG-MAP.mapcore.metacore.dec.biom.txt)

**Comment by HAugustijn** [comment]
From what I can tell, your input files are named something like "100.days.clean.fastq", but your metadata file labels are "100.days", therefore the metadata is not added by BiG-MAP.map. If you either rename your files or adjust the metadata file, your problem should be solved. Additionally, I have now integrated a better error handeling message in BiG-MAP.analyse.

**Comment by razz1618** [comment]
Thanks

**Comment by HAugustijn** [comment]
Did you rerun the mapping module with the correct metadata and using the latest version of BiG-MAP?

**Comment by razz1618** [comment]
I ran the via the old module. with latest module it shows more specific error**The file names are not overlapping with the names in the metadata file. Please provide matching file names. file. Please provide matching file names.**

But even I changed the name in metadata it is showing -The file names are not overlapping with the names in the metadata.

May be I am doing something wrong. My samples are paired end reads named as:

original.bottle.clean_1.fastq
original.bottle.clean_2.fastq
100.days.clean_1.fastq
100.days.clean_2.fastq

So, in metadata do I need to mention both pairs and with the fastq extension or just the sample common name like this:

#run.ID	                        host.ID	   SampleType	        Disease
original.bottle.clean	pcc7002	   METAGENOMIC	0
100.days.clean    	        pcc7002	   METAGENOMIC	100

Thanks,

**Comment by HAugustijn** [comment]
Regarding the metadata, you don't have to include both pairs and the file extensions. In your case, you could use names like: original.bottle.clean
In general, I made an adjustment in the metadata entry system. Are you still having the same problem with the latest version of BiG-MAP.map?

**Comment by razz1618** [comment]
No, i did not resolve. i get the same error with the latest commit. I changed metadata as you suggested. As i see, the error is related to **SampleType** column in the metadata file. The generated biom file do have matching (with the metadata) sample names. 



**Here is the shell otput**

python3 /home/mcs/soft/BiG-MAP/src/BiG-MAP.analyse.py --explore --compare -B 3.Function/antismash/big_map_antismash/mapping/biom-results/BiG-MAP.mapcore.metacore.dec.biom -T Metagenomic -M Status -O 3.Function/antismash/big_map_antismash/results/core_genes

__________Loading biom file_______________________
Traceback (most recent call last):
  File "/home/mcs/soft/BiG-MAP/src/BiG-MAP.analyse.py", line 1185, in <module>
    main()
  File "/home/mcs/soft/BiG-MAP/src/BiG-MAP.analyse.py", line 1049, in main
    biom_dict, args.metagroup)
  File "/home/mcs/soft/BiG-MAP/src/BiG-MAP.analyse.py", line 150, in get_sample_type
    elif sample_type == (sample["metadata"]["SampleType"]).upper():
KeyError: 'SampleType'

I hve uploaded the metadata, biom file and core coverage csv result

[metadata.txt](https://github.com/medema-group/BiG-MAP/files/6790064/metadata.txt)
[BiG-MAP.mapcore.metacore.dec.biom.txt](https://github.com/medema-group/BiG-MAP/files/6790065/BiG-MAP.mapcore.metacore.dec.biom.txt)
[BiG-MAP.map.core.coverage.txt](https://github.com/medema-group/BiG-MAP/files/6790066/BiG-MAP.map.core.coverage.txt)

**Comment by HAugustijn** [comment]
@razz1618 there is a whitespace in front of the identifier “SampleType”, which causes a problem with the analyse module. However, the analyse module is designed to compare two distinct groups. In your case, you have five samples from five different conditions, making the analyse module not the best fitting solution. I recommend to use the outputted TSV files of the map module for your own statistical analyses.
