### ISSUE TITLE
metagenome_contigs

### ISSUE THREAD

**Issue by wisnu-adi** [medema-group/BiG-MAP#9]
Hi there,

Thank you for the awesome tool. I am analysing my shotgun metagenome dataset and have a couple of questions?
1. As I constructed metagenome assembled genomes from the dataset, do you have a recommendation of which MAGs that I should use for BiG-MAP regarding to quality and completeness (HG MAG - 90% with less than 5% contaminants or medium quality is acceptable?)
2. Can we use metagenome contigs instead of genome as an input for big-map?

Best wishes

Wisnu

**Comment by razz1618** [comment]
@wisnu-adi BiG-MAP uses the output of anti- or gutSMASH analysis to cluster BCGs. So, its better to check  anti- or gutSMASH repositories for your query.

 In general, the Lower the completeness lower are the chances to get a complete set of genes. Higher the contamination, the higher the chances of dubious results.  Currently, any bin with at least 70% completion and less than 10% contamination (but not limited to) is considered for downstream analysis as a MAG.

You can use metagenome contigs in  anti- or gutSMASH and feed the output in BiG-MAP.
